- name: install subversion yum repo
  copy: src=wandisco-svn.repo dest=/etc/yum.repos.d

- name: ensure latest subversion source control
  yum: pkg=subversion state=latest

- name: check for existing source checkout
  shell: "[ -d /vagrant/sakai-src ] && echo 'Found' || echo ''"
  register: checkedout_already

- name: checkout Sakai source
  subversion: repo=https://source.sakaiproject.org/svn/sakai/trunk dest=/vagrant/sakai-src force=no
  when: (not checkedout_already.stdout)
